# Generated by Django 5.2.5 on 2025-09-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_magiccode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicCode',
        ),
    ]
