# Generated by Django 5.2.5 on 2025-09-13 12:47

import django.core.validators
import django.db.models.deletion
import moviesite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0005_movie_views_alter_movie_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mpg', 'mov', 'amv', 'mkv', 'avi']), moviesite.models.limit_video, moviesite.models.check_mime], verbose_name='Kinosi'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='user_photo')),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('job', models.CharField(max_length=120)),
                ('website', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=160)),
                ('bio', models.CharField(max_length=350)),
                ('twitter', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('telegram', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('linkedin', models.CharField(blank=True, max_length=90, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
