# Generated by Django 5.2.5 on 2025-09-16 11:58

import django.core.validators
import moviesite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0006_movie_author_alter_movie_video_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release'], 'permissions': [('publish_movie', 'Can publish movie')], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mpg', 'mov', 'amv', 'mkv', 'avi']), moviesite.models.limit_video, moviesite.models.check_mime], verbose_name='Kinosi'),
        ),
    ]
